sudo: required

service:
    - docker

before_install:
    - docker build -t soumya9v/django-postgres-nginx-docker -f Dockerfile.dev .

# if travis return other than 0 means error in script
script:
    - docker run -e CI=true soumya9v/django-postgres-nginx-docker python manage.py test

after_success:
    # - docker build -t soumya9v/multi-client  .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push soumya9v/django-postgres-nginx-docker